package com.jk51.model.orders;

import java.util.Date;

public class SYbMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.buyer_nick
     *
     * @mbg.generated
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.passwd
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.idcard_number
     *
     * @mbg.generated
     */
    private String idcardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.regin_source
     *
     * @mbg.generated
     */
    private Integer reginSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.area
     *
     * @mbg.generated
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.last_ipaddr
     *
     * @mbg.generated
     */
    private String lastIpaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.register_stores
     *
     * @mbg.generated
     */
    private Integer registerStores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.integrate
     *
     * @mbg.generated
     */
    private Long integrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.is_activated
     *
     * @mbg.generated
     */
    private Integer isActivated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yb_member.b_usersarr
     *
     * @mbg.generated
     */
    private String bUsersarr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.member_id
     *
     * @return the value of yb_member.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.member_id
     *
     * @param memberId the value for yb_member.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.buyer_nick
     *
     * @return the value of yb_member.buyer_nick
     *
     * @mbg.generated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.buyer_nick
     *
     * @param buyerNick the value for yb_member.buyer_nick
     *
     * @mbg.generated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.mobile
     *
     * @return the value of yb_member.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.mobile
     *
     * @param mobile the value for yb_member.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.passwd
     *
     * @return the value of yb_member.passwd
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.passwd
     *
     * @param passwd the value for yb_member.passwd
     *
     * @mbg.generated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.last_login
     *
     * @return the value of yb_member.last_login
     *
     * @mbg.generated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.last_login
     *
     * @param lastLogin the value for yb_member.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.name
     *
     * @return the value of yb_member.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.name
     *
     * @param name the value for yb_member.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.sex
     *
     * @return the value of yb_member.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.sex
     *
     * @param sex the value for yb_member.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.idcard_number
     *
     * @return the value of yb_member.idcard_number
     *
     * @mbg.generated
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.idcard_number
     *
     * @param idcardNumber the value for yb_member.idcard_number
     *
     * @mbg.generated
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.regin_source
     *
     * @return the value of yb_member.regin_source
     *
     * @mbg.generated
     */
    public Integer getReginSource() {
        return reginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.regin_source
     *
     * @param reginSource the value for yb_member.regin_source
     *
     * @mbg.generated
     */
    public void setReginSource(Integer reginSource) {
        this.reginSource = reginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.area
     *
     * @return the value of yb_member.area
     *
     * @mbg.generated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.area
     *
     * @param area the value for yb_member.area
     *
     * @mbg.generated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.last_ipaddr
     *
     * @return the value of yb_member.last_ipaddr
     *
     * @mbg.generated
     */
    public String getLastIpaddr() {
        return lastIpaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.last_ipaddr
     *
     * @param lastIpaddr the value for yb_member.last_ipaddr
     *
     * @mbg.generated
     */
    public void setLastIpaddr(String lastIpaddr) {
        this.lastIpaddr = lastIpaddr == null ? null : lastIpaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.birthday
     *
     * @return the value of yb_member.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.birthday
     *
     * @param birthday the value for yb_member.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.register_stores
     *
     * @return the value of yb_member.register_stores
     *
     * @mbg.generated
     */
    public Integer getRegisterStores() {
        return registerStores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.register_stores
     *
     * @param registerStores the value for yb_member.register_stores
     *
     * @mbg.generated
     */
    public void setRegisterStores(Integer registerStores) {
        this.registerStores = registerStores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.create_time
     *
     * @return the value of yb_member.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.create_time
     *
     * @param createTime the value for yb_member.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.update_time
     *
     * @return the value of yb_member.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.update_time
     *
     * @param updateTime the value for yb_member.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.integrate
     *
     * @return the value of yb_member.integrate
     *
     * @mbg.generated
     */
    public Long getIntegrate() {
        return integrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.integrate
     *
     * @param integrate the value for yb_member.integrate
     *
     * @mbg.generated
     */
    public void setIntegrate(Long integrate) {
        this.integrate = integrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.is_activated
     *
     * @return the value of yb_member.is_activated
     *
     * @mbg.generated
     */
    public Integer getIsActivated() {
        return isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.is_activated
     *
     * @param isActivated the value for yb_member.is_activated
     *
     * @mbg.generated
     */
    public void setIsActivated(Integer isActivated) {
        this.isActivated = isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yb_member.b_usersarr
     *
     * @return the value of yb_member.b_usersarr
     *
     * @mbg.generated
     */
    public String getbUsersarr() {
        return bUsersarr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yb_member.b_usersarr
     *
     * @param bUsersarr the value for yb_member.b_usersarr
     *
     * @mbg.generated
     */
    public void setbUsersarr(String bUsersarr) {
        this.bUsersarr = bUsersarr == null ? null : bUsersarr.trim();
    }
}
