spring:
  #redis服务器相关配置
  redis:
      sentinel:
        master: mymaster
        nodes: 172.20.10.192:26379,172.20.10.193:26379
      host: 127.0.0.1
      password:
      port: 6379
      pool:
        min-idle: 20
        max-idle: 200
        max-active: 1024
        max-wait: -1
      timeout: 1000
      #通过@Cacheable代理的缓存默认失效时间(单位：秒)
      cacheableDefaultExpSec: 120
      #设置自定义的缓存失效时间 example1:72，example2:720，...
      expires: weixinjsapi:7200
  thymeleaf:
    # tiles 定义文件所在的位置，多个用逗号隔开如"classpath:/templates/tiles-defs-member.xml,classpath:/templates/tiles-defs-order.xml"
    tilesDefLocations: "classpath:/templates/tiles-defs.xml"
    excludedViewNames: [member/*,demo/*,account/*,login/*]
    cache: false
  datasource:
      dialect: mysql
      url: 
      username: 
      password: 
      driver-class-name: 'com.mysql.jdbc.Driver'
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle : 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      monitorUserName: admin
      monitorPassword: admin
      resetEnable: false
      allow:
      deny:
      exclusions:

  http:
      multipart:
        max-file-size: 200Mb
        max-request-size: 1000Mb
      encoding:
        force: true
server:
  #会话超时时间，原则上要略大于redis session生效时间
  port: 8765
  sessionTimeout: 30
  contextPath: /
  # Tomcat特性相关
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    # secs
    backgroundProcessorDelay: 30

management:
  shell:
    ssh:
      port: 18764
mybatis:
  mapperLocations: classpath:mappers/**/*.xml
  typeAliasesPackage: com.jk51.model
  configuration:
      callSettersOnNulls: true
#配置日志
logging:
  config : classpath:logback-boot.xml
#登录状态拦截
login:
  interceptorEnable: true
  #重定向方式:[forward,redirect]
  redirectType: redirect
  unloginRedirectPath : /
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: false
  params: count=countSql;pageNum=pagenum;pageSize=pagesize
mq:
  namesrvAddr: 172.20.10.164:9876
  producerGroup: CommonsProducer
  timeout: 3000
  retryTimes: 5
pay:
  wxapppay:
        appid: wxa55567499f50f233
        mch_id: 1488814502
        notify_url: https://busm-test.51jk.com/pay/wx/callback
        spbill_create_ip: 172.20.10.92
        key: 3ad7fc467c220508fc4c58227c425wd5
        APPSECRET: e5c05e758781f69355f81120c49f49d9
        cert_path: cert/wx/dev/apiclient_cert_app.p12
        mp_verify_path: cert/wx/dev
  wxpay:
      appid: wx0d296e3b96c559ed
      mch_id: 1509175271
      notify_url: https://busm-test.51jk.com/pay/wx/balanceCallback
      spbill_create_ip: 172.20.10.92
      key: KVBHTUKu6834h34lvermnibn0974323v
      APPSECRET: a2f6a41c4302c15733acd61f097e3339
      cert_path: cert/wx/dev/apiclient_cert_new51.p12
      mp_verify_path: cert/wx/dev
  wxxcxpay:
        appid: wx07bc1f46002fd3f8
        mch_id: 1270277701
        notify_url: http://busm-test.51jk.com/pay/wx/callback
        spbill_create_ip: 172.20.12.71
        key: 26489da6f1265e4901ffb80afaa36111
        APPSECRET: 6cf32df61cb4df4f240f8b5ed91df1c2
        cert_path: cert/wx/dev/apiclient_cert.p12
        mp_verify_path: cert/wx/dev
        xcxappid: wx22aadc4e03be7771
        xcxappsecret: 1352afcb4a9b333ede02eb5409bb1286
  wxpay51jk:
      appid: wxa71df64493d907d1
      mch_id: 1250072101
      notify_url: https://busm-test.51jk.com/pay/wx/callback
      spbill_create_ip: 172.20.12.71
      key: eXC05UrwOy8whSo6mV4O4YzmFieZ2cGd
      APPSECRET: 244c15e4e70e679778958b6ceea05c73
      cert_path: cert/wx/dev/apiclient_cert_51jk.p12
      mp_verify_path: cert/wx/dev
  wxpayfw:
          appid: wx0d296e3b96c559ed
          mch_id: 1509173571
          notify_url: https://busm-test.51jk.com/pay/wx/callback
          spbill_create_ip: 172.20.10.92
          key: JNDELmcv5470GkouitFhuh6FFPDHKOi6
          APPSECRET: a2f6a41c4302c15733acd61f097e3339
          cert_path: cert/wx/dev/apiclient_cert_fwnew51.p12
          mp_verify_path: cert/wx/dev
  alipay:
    app_id: 2018071260607037
    seller_id: wuyi@51jk.com
    private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCEFH/cF0CLVWUIecs51l7A/jP7A0ZHd+Epu5+lHzrk/GXIoF4+BEIEp9k+VPl4q/6WFGsnuJaLqMhzI4tGDCheFg48TtnVkSnpAA1rJM67PfpRv2Vpyl6Ci35zXlqDL49KMToX61flY/HRLuQfM8JhJFEPuJUE7H/obAtrfWU95dtuP+x7w7XP25mQ2243AxURGuB0PHHdAsxitKII0aKrf73XHUhJ1E/6+RWdj74vTH2GkrgMr48E3K5ZEn4SF5O8Dlksl93nvEGSoTBcr875qoHvyBYXDnMEo+O46Di/4K8YXEXM4XQSboRBIwMzYweHjZaBiHEuLM5OeFQcxRANAgMBAAECggEAJ2kCecaKYMjbO7szs49OeKGhGv3wI3UWv2AXk6qM5TSWnlWTqUeV91OqE9pBEguoDFoNWy3N5eA353ssnHsWNHS6TK5uezY0XizA1D6IXQByR6Anf3h92NAMrBn0Qf6X79hecDKt6Gl5ByTJtrG4B0pR0bIO7QgwZkaO5cTlx6D3quaiIiwkhY3eD5eBf6V8L4FC1fr9W/c0ZL9QY24oX4QTdMloJ+15XyOU0ZZlG6/xry2AeGuAMl8Y2fdt/iijud6W0GSlYE+Ll+qbNGfSjkpHPqHX0Y6s/Jr8n1euItQ7T6QdXnusWVfCNYHZoJMwjkrzdiYe5ZNzJvazn/G+gQKBgQC4835F87q1MZhIMN+eUUqDyplGxDkEFRCIrRVK12IqyidNkv3Hxb6ugU5dQNerfgSGVivjtIjYnrr8PPsRefab621klEVfWz7pQZRRR/OWaFsA8wR/L4ca3CpIG765xnUGwLhcsRwA6NMC0GUL6zt2gla7dzrm5NUlmLPGzpVtoQKBgQC20Yw2IddMf867YdJ0n3kug9HpMA++R6hR+sY/APbfvNdR0U0c37O+S1MJCqJHr1fJv2UymkM3nI+y6E/SbHKvcI+PsAmhm5kWL75Sd6cQ4u/Wv+AVUljZoI/La0ERLyRwbl/PQirexcxQ15LDUSaR4MmmwJq9JmxmMBTfU7FS7QKBgDXjRDxvekwG6j7GdrEzMEncAvLag15MIOghvh1zSff7tJ3moSjO1fMUW9fR58Tgz8KwYtNSq7ip7wNFZUW/Sno9iz8N8HSLKnZeFC/mjfOZ7kIFjJ7eIzhRQ8SEyPpp93kDN/RR6j3dmHWucHKblFTAPzMZ10ClFfGBX4giculhAoGBAJ+ZLdtwDaG2Dccd7flr4wHNiGoXUBcgPXxb/cew0tSd6id+HeCwFh1xaqsBAoysMWpp0TGs5DNfVT+teUnM7Q3lqR6aYr4XtTxeL7uUw1+FjjWeykQy4GgUuJOwLVyQGDKi2Ld6Hyzd5rFIkNI8PPyrDb+qcyvfqFBJd19DlBE9AoGBALgdyBjqnCL4U01BWWlUfVdObZQHztBb/CnV1dMDTJ3iqn5cb0psxrkz97euLGxmvPSots44bD+n1Y2bI3L+dd4f5jAJodiRZ6H7dMEXrznXdIHRAjpm7Krepum/u+3ZlokC9oB319aHv3JzJ5LxQt733Vqnf2t6Pw7XJTUHoskF
    ali_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiZqW5dugitE2dCWNJ+MZBuxmAAWGkbwfNutJRGDSQgT6dw43z0ZJLk8x24E/4Hq84Oz1u2/h0IspISJcQA/0qE9yvX0N3YTJwrQguLk8yd8pMyOpOVbr2T04YVyRKFoXH7qRNhp1P46inHegLAe5q8rCDzfKtPvsXUymCNQE432QyH2UF5uvVGTfbSjBeiyxc2YM5T3sgFJxT8rnkFgU8loqKgdK8+bJizXQHRbP3L8z1YmX5ErLszz3UUGd8lrhjTkR+HQTsJggxUrqIvPFpiW6DTvJ1ynBNBNofeXS5cdzOi8MORJc6N99ydX/ZCTJWqcfX5/siZQlBiFrGQkjvQIDAQAB
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhBR/3BdAi1VlCHnLOdZewP4z+wNGR3fhKbufpR865PxlyKBePgRCBKfZPlT5eKv+lhRrJ7iWi6jIcyOLRgwoXhYOPE7Z1ZEp6QANayTOuz36Ub9lacpegot+c15agy+PSjE6F+tX5WPx0S7kHzPCYSRRD7iVBOx/6GwLa31lPeXbbj/se8O1z9uZkNtuNwMVERrgdDxx3QLMYrSiCNGiq3+91x1ISdRP+vkVnY++L0x9hpK4DK+PBNyuWRJ+EheTvA5ZLJfd57xBkqEwXK/O+aqB78gWFw5zBKPjuOg4v+CvGFxFzOF0Em6EQSMDM2MHh42WgYhxLizOTnhUHMUQDQIDAQAB
    notify_url: https://busm-test.51jk.com/pay/ali/balanceCallback
    log_path: /aliPayLog
    url: https://openapi.alipay.com/gateway.do
    return_url: http://busm-test.51jk.com
    charset: UTF-8
    sign_type: RSA2
    format: json
  alipayfw:
    app_id: 2018070960520703
    seller_id: wuyi@51jk.com
    private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2Y6XHjSTaGfLeFYgzjVDhqWIgF7SDaokL3dsnjyenme4IGrtrx/Kcyy9fLrwbaaRIyXOltWJENwKPE/oisEKaDqL/5CxLRle24Xa9QEK4XXQdli7xokblbELnRt5Q6GByzHVu7KP+gJxzrAVwR139Zsl2u5AI6EQkxfE7FVkuOIo06S0sYCeIfkjpoeCKzkJZHx0DezGHSr98C1BA+UJ3bM+xP8EYBHXMBut7ZDJ8Cenqz5fbF8cPT4rs98OlODFm3aui3/NchO/hB4W3UTICQbLgygEdbIcRpKrv9nOOw6pPJA2C03uyAM/nxli8rdxfeAbsO1ZbTignxT8ChnDxAgMBAAECggEANijvAIvMJqvP79zK/iv3mZsX1VnUs7V+DrUJr/yVlPJjuapef0n3pFG9tnEFUMqVCzwvCEUNch43t08CVyyqCl9QTdZuxMeVomvfO6GKbn7pzSNcu0op7VSxpUXpHHN0uII4WQESTa/ZRYwObWHz6hyMtKJLyilWmujgkl/rhIqpcDZjJ0r25B0XxsyGSZLcm6CgzFmRCmmGwvKTTfRRw8aue/nGlMl5m01hxtcfyawCC/47XWXl/dDeFoK41CiWEglw6OBfn9PGvnpdGkJXA8pYqh1ueRBL1t0crd5OlU47XMwXtC7euHXg/MGV4w+6OaOKjrNeeQLIno/jSyqHxQKBgQD/slUYNq+9Xxqt8y6hGCReGC26uE5HuubexpZWOj86/CBGv3Ssovo4rHJby0LIHHZUWA+gPQk2CHeuw1dXjIp/FdRIgbud+WzNwJuCm4iQ4YKFiByZcHn93pOTljJMA6DH7vTVY9V30ueB1k0gyblgWMdBDkmVq/7V48wgG4r7uwKBgQC2mwxSjaljRIbtOCPOfSH2sJvEzt+m1DxmFt/1gd775CkvchlXia2+g5t+H7H9D+BAonCFvl/Dosq07k1i8UMaPf7Py3MfW93++XTzF18CGe2RLt79YW4tLnn6aTW2IWBcFLYFJMksuZ0e1c9sviUME48HbQbnIWVEl+snC1E9QwKBgQDldmdRFHp/qmJp6otU/DJe0rnvD8kILB1VnMd7WEg4KdzZQKV268c7pt31rKIgrRIvvNtBBKVIfS7SgfDW24PKao+YBfyV1ymiN5AXFHbo9cdJCA4KUNrZTa4IS0iV2MenxLSo7y+5mWYyqVuL6hvW77TYl/bHP5Ow5P3hbnY6UwKBgHVot8GUqCbVdtOr1wn7Vw0gfOdMBG1l5PfXGWTnfhIDn5+MA1NPiNEIGcA8bNrDjHLCfwrfXv+Q+jjfSA6oBXcoCWBd9cVh8hjxGAr9Ke9V8HP66RGNxaNzUKZ7YzeZujU6c9ZW0qrZJXcgDmBi2bssEDi8F0YhKNWzwFS4aCG1AoGBAMGdBanFCT9B62G7MlBWR3aw5cU3gq2eMBdSbdHoGCMBl1Y5WlG0mIuoQ5F1QGg5nTYaabChIqEuSqRmk8Iccm2Yw6zIq+tJfZ9G3rYEXDFaYdWX2RiYdD5mRyaz7EzdNnknslaCb9Dx6+2r4YMpA2ILd3mJZU1D1qA9TZ6oLD6H
    ali_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiZqW5dugitE2dCWNJ+MZBuxmAAWGkbwfNutJRGDSQgT6dw43z0ZJLk8x24E/4Hq84Oz1u2/h0IspISJcQA/0qE9yvX0N3YTJwrQguLk8yd8pMyOpOVbr2T04YVyRKFoXH7qRNhp1P46inHegLAe5q8rCDzfKtPvsXUymCNQE432QyH2UF5uvVGTfbSjBeiyxc2YM5T3sgFJxT8rnkFgU8loqKgdK8+bJizXQHRbP3L8z1YmX5ErLszz3UUGd8lrhjTkR+HQTsJggxUrqIvPFpiW6DTvJ1ynBNBNofeXS5cdzOi8MORJc6N99ydX/ZCTJWqcfX5/siZQlBiFrGQkjvQIDAQAB
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmOlx40k2hny3hWIM41Q4aliIBe0g2qJC93bJ48np5nuCBq7a8fynMsvXy68G2mkSMlzpbViRDcCjxP6IrBCmg6i/+QsS0ZXtuF2vUBCuF10HZYu8aJG5WxC50beUOhgcsx1buyj/oCcc6wFcEdd/WbJdruQCOhEJMXxOxVZLjiKNOktLGAniH5I6aHgis5CWR8dA3sxh0q/fAtQQPlCd2zPsT/BGAR1zAbre2QyfAnp6s+X2xfHD0+K7PfDpTgxZt2rot/zXITv4QeFt1EyAkGy4MoBHWyHEaSq7/ZzjsOqTyQNgtN7sgDP58ZYvK3cX3gG7DtWW04oJ8U/AoZw8QIDAQAB
    notify_url: https://busm-test.51jk.com/pay/ali/callback
    pnotify_url: https://busm-test.51jk.com/pay/ali/callbackfw
    log_path: /aliPayLog
    url: https://openapi.alipay.com/gateway.do
    return_url: http://busm-test.51jk.com
    charset: UTF-8
    sign_type: RSA2
    format: json
  unipay:
    merId: 777290058143717
    frontUrl: http://goodsService-dev.51jk.com/pay/uni/frontrec
    backUrl: http://goodsService-dev.51jk.com/pay/uni/backrec
    frontRequestUrl: https://101.231.204.80:5000/gateway/api/frontTransReq.do
    backRequestUrl: https://101.231.204.80:5000/gateway/api/backTransReq.do
    signCertPath: cert/uni/dev/700000000000001_acp.pfx
    signCertPwd: "000000"
    signCertType: PKCS12
    validateCertDir: cert/uni/dev
    validateCertPath: cert/uni/dev/verify_sign_acp.cer
#地图接口配置
mapConfig:
    GEO_KEY: 137816363e19388eae9c693ebe9281ce
    BD_KEY: rtKe2Gm1Q3d0HwBMWLKlPY4prIC6CEQU
    geoDistance: http://restapi.amap.com/v3/direction/walking?origin=%s&destination=%s&key=%s
    geoCoordinate: http://restapi.amap.com/v3/geocode/geo?address=%s&output=json&key=%s
    regeo: http://restapi.amap.com/v3/geocode/regeo?output=json&location=%s|%s&extensions=base&batch=true&key=%s
    bdCoordinate: http://api.map.baidu.com/geocoder/v2/?address=%s&output=json&ak=%sa
    regeoA: http://restapi.amap.com/v3/geocode/regeo?output=json&location=%s&extensions=base&batch=true&key=%s

#短信接口配置文件
sms:
  #容联云通信接口
  ytx:
    ytx_sms_url: app.cloopen.com
    ytx_sms_port: 8883
    ytx_sms_sid: 8a216da855e425d60155e89123920433
    ytx_sms_token: 6d15b298163a4f35ba404ddfebe421dd
    ytx_sms_appid: 8a216da855e425d60155e89123f60439
    ytx_sms_valid_min: 10
    ytx_sms_tempid_regcode: 1
    ytx_sms_tempid_msg: 2
    ytx_sms_yu_appid: 8a216da85f52c168015f567f99fb00de
  #云片云通信接口
  yp:
    yp_sms_url: https://sms.yunpian.com/v2/sms/tpl_single_send.json
    yp_sms_appkey: 1bf35fad03e33d7f8216a73c65f36621
  #上海助通短信+语音接口
  zt:
    zt_sms_url: http://www.ztsms.cn/sendNSms.do?username=%s&password=%s&tkey=%s&mobile=%s&content=%s&productid=%s&xh=
    zt_yysms_url: http://www.yzmsms.cn/sendSmsYY.do?username=%s&password=%s&tkey=%s&mobile=%s&content=%s
    zt_sms_username: yltzgl
    zt_sms_password: yRM9ZGIxgZ9cPdZvl3pnLrJPd
  #点集通信开发接口
  dj:
    dj_sms_url: http://sapi.appsms.cn:8088/msgHttp/json/mt?account=%s&password=%s&mobile=%s&content=%s&timestamps=%s
    dj_sms_username: 51jiankang106fY23
    dj_sms_password: XFUn6vqZ
  #7moor请求配置
  _7moor:
    accountID: N00000011574
    password: 1255Edpv
    apisecret: 57d182d0-d30e-11e6-98ab-b97a87981f3b
    url_temp: http://apis.7moor.com/v20160818/sms/getSmsTemplate/%s?sig=%s
    url_sms:  http://apis.7moor.com/v20160818/sms/sendInterfaceTemplateSms/%s?sig=%s
    url_web_call: http://busm-test.51jk.com/common/recall
    action: WebCall
    PBX: sh.ali.7.0
    serviceNo: 02126125865
    timeout: 20
    maxCallTime: 60
  #微信公众号
  sdk:
    grant_type: ybzf_weixin_token
    appid: wxdd1f573ca4306c58
    secret: 3e68f86e2721b85546aa6c1e592bc0fc

trades:
  systemCanel: 1   #未付款
  systemConfirm: 3  #门店自提|直购
  systemDelivery: 7  #送货上门
  ytx_sms_tempid_msg: 2
  trades_end: -15
#文件上传服务
fileserver:
  baseserver: http://img-dev.51jk.com
  uploadimageurl: ${fileserver.baseserver}/api/upload

#搜索服务
search:
  addr: http://172.20.10.150:9201


#容联IM配置信息
rlim:
  accountSid: 8a216da855e425d60155e89123920433
  authToken: 6d15b298163a4f35ba404ddfebe421dd
  baseUrl: https://app.cloopen.com:8883/2013-12-26
#report临时文件夹
report:
  temp_dir: ../reports

#蜂鸟配送配置信息
ele:
  appId: 35ade6eb-deb5-4669-baf5-e394a80e4916
  secretKey: ed7ac534-de2b-4bd0-bf18-57436458f657
  api_url: https://open-anubis.ele.me/anubis-webapi
  notify_url: http://busm-test.51jk.com/common/notifyOrderStatus

#达达物流配置信息
imdada:
  app_key: dada52897adb4e86da6
  app_secret: 2e8bd12f4c8d87d3f02c08c2846e7be1
  source_id: 1139
  allow_site: 100166
  api_domain: http://newopen.imdada.cn
  notify_url: http://busm-test.51jk.com/common/cb

erp:
  is_open: false
  storage_service_url : http://172.20.10.161:8765/offline/storage
  service_url: http://172.20.10.161:8765
  jiuzhou: http://122.225.202.20:18080/ExService
  qianjin: http://218.75.221.60:8003/servlet
  tianrun: http://61.160.106.235:9300/HuiyInfoQuery/service
flyway:
  baselineOnMigrate: false
  enabled: false
 #个推参数
getui:
  appId: 3CF3zVF2PP74msdqd2amx4
  AppSecret: g9QqoFJsGa7lsr1QoK5mg3
  appKey: 3HyjhdO2oS9BwLPOVFmwf9
  masterSecret: wJal692RWo6qFkDPEcXBw7

#优惠券URL
coupon:
  triggerCouponUrl: .weixin-test.51jk.com/

#mns管理
mns:
  MNSEndpoint: 'http://1704256822322729.mns.cn-hangzhou.aliyuncs.com/'
  accessId: 'LTAIxqQBJq89MWnA'
  accessKey: '4dITLAdbiBCr0mgXtY3Ne3Ocm9uvde'

#ES配置
es:
   cluster:
    host: 172.20.10.150
    port: 9301
    name: 150Test
   goods:
    index: 51jk-goods
   suggest:
    index: 51jk-suggest
   shopname: b_shop_

#人脸识别配置
detect:
    tencentAppKey: 8HVmoEJfp93ULjfw
    tencentAppId: 1106701656

#OSS图片管理
oss:
  endpoint: 'oss-cn-shanghai.aliyuncs.com'
  accessKeyId: 'LTAIxqQBJq89MWnA'
  accessKeySecret: '4dITLAdbiBCr0mgXtY3Ne3Ocm9uvde'
  bucketName: 'jkosshash'
  imgUrl: 'oss-cn-shanghai.aliyuncs.com'

#网易im
netease:
  appkey: 32128271f04c17e8f2d151134e128074
  appSecret: 47a64cd589f3
  nonce: 12345
