package com.jk51.modules.persistence.mapper;


import com.jk51.model.orders.SYbMember;

import java.util.Map;

public interface SYbMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int insert(SYbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int insertSelective(SYbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    SYbMember selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SYbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SYbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SYbMember record);

    SYbMember selectByMobile(String memberId);

    Integer selectCountByMobile(String memberId);

    int updateIdCardNumber(Map map);

}
