package com.jk51.modules.notice.mapper;

import com.jk51.model.Upgrade;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UpgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int insert(Upgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int insertSelective(Upgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    Upgrade selectByPrimaryKey(Integer id);

    Upgrade selectByCreateTime(@Param("type") int type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Upgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Upgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_51jk_upgrade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Upgrade record);

    List<Upgrade> getUpgradeGroup(Map<String,Object> params);

    int deleteUpgradeByPrimaryKey(Map<String,Object> params);
}