package com.jk51.modules.registration.mapper;

import com.jk51.model.registration.models.ServceUseDetail;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;
@Mapper
public interface ServceUseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    int insert(ServceUseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    int insertSelective(ServceUseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    ServceUseDetail selectByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServceUseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_use_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServceUseDetail record);


    /**
     * 查询每一个模版的子项
     * @param siteId
     * @param templateNo
     * @param templateId
     * @param goodsId
     * @param useTime
     * @return
     */
    ServceUseDetail selectByTemplateNoAndTemplateId(@Param("siteId") Integer siteId,
                                                    @Param("templateNo") String templateNo,
                                                    @Param("templateId") Integer templateId,
                                                    @Param("goodsId") Integer goodsId,
                                                    @Param("useTime") Date useTime);

    /**
     *@param  paramMap
     * return list
     */

    List<Map<String,Object>> queryallServceOrderDetailList(Map<String,Object> paramMap);

    /**
     *@param  paramMap
     * return map
     */

    Map<String,Object> subscribMsgDetail(Map<String,Object> paramMap);



    /**
     * 查询商家医生的当天的所有正常排班
     * @param siteId
     * @param goodsId
     * @param useTime
     * @return
     */
    List<ServceUseDetail> selectByUseTime(@Param("siteId") Integer siteId, @Param("goodsId") Integer goodsId,
                                          @Param("useTime") Date useTime);


    /**
     * 获取医生一个月的排班
     * @param siteId
     * @param goodsId
     * @param startTime
     * @param endTime
     * @return
     */
    Map<String,Object> selectAllMineClassesByGoodsId(@Param("siteId") Integer siteId, @Param("goodsId") Integer goodsId,
                                          @Param("startTime") Date startTime,@Param("endTime") Date endTime);

    /**
     * 一个月的排班
     * @param paramMap
     * @return
     */
    List<Map<String,Object>> selectAllMineClassesByGoods(Map<String,Object> paramMap);

    /**
     * 修改 下单后，预约数+1
     * @param servceUseDetail
     */
    Integer updateByTemplateNoAndMineClassesId(ServceUseDetail servceUseDetail);
}