package com.jk51.modules.registration.mapper;

import com.jk51.model.registration.models.ServceDoctor;
import com.jk51.modules.registration.request.DoctorAndGoodS;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface ServceDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int insert(ServceDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int insertSelective(ServceDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    ServceDoctor selectByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServceDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ServceDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_servce_doctor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServceDoctor record);

    List<ServceDoctor> findDoctorInfo(ServceDoctor doctor);

    /**
     *@param  paramMap
     * return list
     */

    List<Map<String,Object>> queryDoctorForServceOrderMsg(Map<String,Object> paramMap);

    List<DoctorAndGoodS> selectDoctorAndGoods(DoctorAndGoodS doctor);
}