package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.IconLink;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface IconLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("linkId") Integer linkId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    int insert(IconLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    int insertSelective(IconLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    IconLink selectByPrimaryKey(@Param("linkId") Integer linkId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IconLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_iconlink
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IconLink record);

    /**
     * 获取全部的icon链接信息
     *
     * @return
     */
    List<IconLink> getList(@Param("siteId") Integer siteId);

    List<IconLink> getIconLinksBySiteId(@Param("siteId") Integer siteId);
}
