package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.MerchantSetting;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int insert(MerchantSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int insertSelective(MerchantSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    MerchantSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MerchantSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MerchantSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yb_merchant_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MerchantSetting record);

    List<MerchantSetting> getMetasSiteId(@Param("siteId") Integer siteId);
}
