package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.OrdersTreat;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrdersTreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    int insert(OrdersTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    int insertSelective(OrdersTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    OrdersTreat selectByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrdersTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrdersTreat record);

    /**
     * 根据条件（siteID，orderId，goods_id）更新批号等信息
     *
     * @param orders
     * @return
     */
    Integer updateByProperties(OrdersTreat orders);

    /**
     * 根据siteID，orderId，goods_id 获取order信息
     * @param orders
     * @return
     */
    OrdersTreat getGoodsBatchsNo(OrdersTreat orders);
}
