package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.WxAdvertise;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WxAdvertiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer siteId, Integer ads_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    int insert(WxAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    int insertSelective(WxAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    WxAdvertise selectByPrimaryKey(@Param("siteId") Integer siteId, @Param("adsId") Integer ads_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_ads
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxAdvertise record);

    /**
     * 获取全部的微信滑动广告
     * @param siteId
     * @return
     */
    List<WxAdvertise> getSlideList(@Param("siteId") Integer siteId);

    /**
     * 增加一个微信滑动广告
     * @param advertise
     * @return
     */
    int addSlideAdvertisemet(WxAdvertise advertise);

    /**
     * 更新一个微信滑动广告
     * @param advertise
     * @return
     */
    int updateSlideAdvertisemet(WxAdvertise advertise);

    /**
     * 删除一个微信滑动广告 --逻辑删除
     * @param siteId
     * @param ads_id
     * @return
     */
    int deleteSlideAdvertisemet(@Param("siteId") Integer siteId, @Param("adsId") Integer ads_id);

    /**
     * 获取全部的微信分类广告
     * @param siteId
     * @return
     */
    List<WxAdvertise> getClassifyList(@Param("siteId") Integer siteId);

    List<WxAdvertise> getWxAdvertiseListBySiteId(@Param("siteId") Integer siteId);
}
