package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.WxAutoReply;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxAutoReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int insert(WxAutoReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int insertSelective(WxAutoReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    WxAutoReply selectByPrimaryKey(@Param("id") Integer id, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxAutoReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WxAutoReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_autoreply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxAutoReply record);

    /***
     * 关注后的回复信息
     *
     * @param siteId
     * @param replyType
     * @return
     */
    WxAutoReply selectByAttention(@Param("siteId") Integer siteId, @Param("replyType") Integer replyType,@Param("isdel") Integer isdel);

    /**
     * 更新关注的自动回复
     *
     * @param wxAutoReply
     * @return
     */
    Integer updateAttention(WxAutoReply wxAutoReply);

    /**
     * 默认的自动回复信息
     *
     * @param siteId
     * @param replyType
     * @return
     */
    WxAutoReply defaultReply(@Param("siteId") Integer siteId, @Param("replyType") Integer replyType,@Param("isdel") Integer isdel);

    /**
     * 更新默回复的信息
     *
     * @param wxAutoReply
     * @return
     */
    Integer updateDefaultReply(WxAutoReply wxAutoReply);

    /**
     * 获取所有的关键字回复
     *
     * @param siteId
     * @param replyType
     * @return
     */
    List<WxAutoReply> getImportWordList(@Param("siteId") Integer siteId, @Param("replyType") Integer replyType);

    /**
     * 一键启动
     * @param onOff
     * @param siteId
     * @return
     */
    Integer turnOnOff(@Param("onOff") Integer onOff, @Param("siteId") Integer siteId);
}
