package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.WXPictureContext;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WxPictureContextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("picContextId") Integer picContextId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int insert(WXPictureContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int insertSelective(WXPictureContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    WXPictureContext selectByPrimaryKey(@Param("picContextId") Integer picContextId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WXPictureContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WXPictureContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic_context
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WXPictureContext record);

    List<WXPictureContext> getList();
}