package com.jk51.modules.treat.mapper;

import com.jk51.model.treat.WXPicture;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("picId") Integer picId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    int insert(WXPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    int insertSelective(WXPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    WXPicture selectByPrimaryKey(@Param("picId") Integer picId, @Param("siteId") Integer siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WXPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_wx_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WXPicture record);

    /**
     *
     * 
     * @param i
     * @return
     */
    List<WXPicture> getList(int i);

    /**
     * 根据mediaId获取本地url地址
     *
     * @param mediaId
     * @return
     */
    String getByMediaId(String mediaId);
}
