package com.jk51.model.treat;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class IconLib {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.icon_id
     *
     * @mbg.generated
     */
    @JsonProperty("iconId")
    private Integer iconId;

    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.site_id
     *
     * @mbg.generated
     */
    @JsonProperty("siteId")
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.icon_img_url
     *
     * @mbg.generated
     */
    @JsonProperty("iconImgUrl")
    private String iconImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.icon_is_system
     *
     * @mbg.generated
     */
    @JsonProperty("iconIsSystem")
    private Integer iconIsSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.create_time
     *
     * @mbg.generated
     */
    @JsonProperty("createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlib.update_time
     *
     * @mbg.generated
     */
    @JsonProperty("updateTime")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.icon_id
     *
     * @return the value of b_iconlib.icon_id
     *
     * @mbg.generated
     */
    public Integer getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.icon_id
     *
     * @param iconId the value for b_iconlib.icon_id
     *
     * @mbg.generated
     */
    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.site_id
     *
     * @return the value of b_iconlib.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.site_id
     *
     * @param siteId the value for b_iconlib.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.icon_img_url
     *
     * @return the value of b_iconlib.icon_img_url
     *
     * @mbg.generated
     */
    public String getIconImgUrl() {
        return iconImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.icon_img_url
     *
     * @param iconImgUrl the value for b_iconlib.icon_img_url
     *
     * @mbg.generated
     */
    public void setIconImgUrl(String iconImgUrl) {
        this.iconImgUrl = iconImgUrl == null ? null : iconImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.icon_is_system
     *
     * @return the value of b_iconlib.icon_is_system
     *
     * @mbg.generated
     */
    public Integer getIconIsSystem() {
        return iconIsSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.icon_is_system
     *
     * @param iconIsSystem the value for b_iconlib.icon_is_system
     *
     * @mbg.generated
     */
    public void setIconIsSystem(Integer iconIsSystem) {
        this.iconIsSystem = iconIsSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.create_time
     *
     * @return the value of b_iconlib.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.create_time
     *
     * @param createTime the value for b_iconlib.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlib.update_time
     *
     * @return the value of b_iconlib.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlib.update_time
     *
     * @param updateTime the value for b_iconlib.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getLinkName() {
        return linkName;
    }

    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }
}