package com.jk51.model.treat;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class IconLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_id
     *
     * @mbg.generated
     */
    @JsonProperty("linkId")
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.site_id
     *
     * @mbg.generated
     */
    @JsonProperty("siteId")
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.icon_id
     *
     * @mbg.generated
     */
    @JsonProperty("iconId")
    private Integer iconId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_name
     *
     * @mbg.generated
     */
    @JsonProperty("linkName")
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_url
     *
     * @mbg.generated
     */
    @JsonProperty("linkUrl")
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_status
     *
     * @mbg.generated
     */
    @JsonProperty("linkStatus")
    private Integer linkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_sort
     *
     * @mbg.generated
     */
    @JsonProperty("linkSort")
    private Integer linkSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_item_num
     *
     * @mbg.generated
     */
    @JsonProperty("linkItemNum")
    private Integer linkItemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.link_type
     *
     * @mbg.generated
     */
    @JsonProperty("linkType")
    private Integer linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.platform_type
     *
     * @mbg.generated
     */
    @JsonProperty("platformType")
    private Integer platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.create_time
     *
     * @mbg.generated
     */
    @JsonProperty("createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_iconlink.update_time
     *
     * @mbg.generated
     */
    @JsonProperty("updateTime")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_id
     *
     * @return the value of b_iconlink.link_id
     *
     * @mbg.generated
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_id
     *
     * @param linkId the value for b_iconlink.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.site_id
     *
     * @return the value of b_iconlink.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.site_id
     *
     * @param siteId the value for b_iconlink.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.icon_id
     *
     * @return the value of b_iconlink.icon_id
     *
     * @mbg.generated
     */
    public Integer getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.icon_id
     *
     * @param iconId the value for b_iconlink.icon_id
     *
     * @mbg.generated
     */
    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_name
     *
     * @return the value of b_iconlink.link_name
     *
     * @mbg.generated
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_name
     *
     * @param linkName the value for b_iconlink.link_name
     *
     * @mbg.generated
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_url
     *
     * @return the value of b_iconlink.link_url
     *
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_url
     *
     * @param linkUrl the value for b_iconlink.link_url
     *
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_status
     *
     * @return the value of b_iconlink.link_status
     *
     * @mbg.generated
     */
    public Integer getLinkStatus() {
        return linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_status
     *
     * @param linkStatus the value for b_iconlink.link_status
     *
     * @mbg.generated
     */
    public void setLinkStatus(Integer linkStatus) {
        this.linkStatus = linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_sort
     *
     * @return the value of b_iconlink.link_sort
     *
     * @mbg.generated
     */
    public Integer getLinkSort() {
        return linkSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_sort
     *
     * @param linkSort the value for b_iconlink.link_sort
     *
     * @mbg.generated
     */
    public void setLinkSort(Integer linkSort) {
        this.linkSort = linkSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_item_num
     *
     * @return the value of b_iconlink.link_item_num
     *
     * @mbg.generated
     */
    public Integer getLinkItemNum() {
        return linkItemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_item_num
     *
     * @param linkItemNum the value for b_iconlink.link_item_num
     *
     * @mbg.generated
     */
    public void setLinkItemNum(Integer linkItemNum) {
        this.linkItemNum = linkItemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.link_type
     *
     * @return the value of b_iconlink.link_type
     *
     * @mbg.generated
     */
    public Integer getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.link_type
     *
     * @param linkType the value for b_iconlink.link_type
     *
     * @mbg.generated
     */
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.platform_type
     *
     * @return the value of b_iconlink.platform_type
     *
     * @mbg.generated
     */
    public Integer getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.platform_type
     *
     * @param platformType the value for b_iconlink.platform_type
     *
     * @mbg.generated
     */
    public void setPlatformType(Integer platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.create_time
     *
     * @return the value of b_iconlink.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.create_time
     *
     * @param createTime the value for b_iconlink.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_iconlink.update_time
     *
     * @return the value of b_iconlink.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_iconlink.update_time
     *
     * @param updateTime the value for b_iconlink.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}