package com.jk51.model.treat;

import java.util.Date;

public class OldAdvertisement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.adv_id
     *
     * @mbg.generated
     */
    private Integer advId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.slide_oneimg
     *
     * @mbg.generated
     */
    private String slideOneimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.slide_oneurl
     *
     * @mbg.generated
     */
    private String slideOneurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.slide_sort
     *
     * @mbg.generated
     */
    private Integer slideSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.slide_type
     *
     * @mbg.generated
     */
    private Integer slideType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.ad_status
     *
     * @mbg.generated
     */
    private Integer adStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.platform_type
     *
     * @mbg.generated
     */
    private Integer platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_adverisement.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.adv_id
     *
     * @return the value of b_adverisement.adv_id
     *
     * @mbg.generated
     */
    public Integer getAdvId() {
        return advId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.adv_id
     *
     * @param advId the value for b_adverisement.adv_id
     *
     * @mbg.generated
     */
    public void setAdvId(Integer advId) {
        this.advId = advId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.slide_oneimg
     *
     * @return the value of b_adverisement.slide_oneimg
     *
     * @mbg.generated
     */
    public String getSlideOneimg() {
        return slideOneimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.slide_oneimg
     *
     * @param slideOneimg the value for b_adverisement.slide_oneimg
     *
     * @mbg.generated
     */
    public void setSlideOneimg(String slideOneimg) {
        this.slideOneimg = slideOneimg == null ? null : slideOneimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.slide_oneurl
     *
     * @return the value of b_adverisement.slide_oneurl
     *
     * @mbg.generated
     */
    public String getSlideOneurl() {
        return slideOneurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.slide_oneurl
     *
     * @param slideOneurl the value for b_adverisement.slide_oneurl
     *
     * @mbg.generated
     */
    public void setSlideOneurl(String slideOneurl) {
        this.slideOneurl = slideOneurl == null ? null : slideOneurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.slide_sort
     *
     * @return the value of b_adverisement.slide_sort
     *
     * @mbg.generated
     */
    public Integer getSlideSort() {
        return slideSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.slide_sort
     *
     * @param slideSort the value for b_adverisement.slide_sort
     *
     * @mbg.generated
     */
    public void setSlideSort(Integer slideSort) {
        this.slideSort = slideSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.slide_type
     *
     * @return the value of b_adverisement.slide_type
     *
     * @mbg.generated
     */
    public Integer getSlideType() {
        return slideType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.slide_type
     *
     * @param slideType the value for b_adverisement.slide_type
     *
     * @mbg.generated
     */
    public void setSlideType(Integer slideType) {
        this.slideType = slideType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.ad_status
     *
     * @return the value of b_adverisement.ad_status
     *
     * @mbg.generated
     */
    public Integer getAdStatus() {
        return adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.ad_status
     *
     * @param adStatus the value for b_adverisement.ad_status
     *
     * @mbg.generated
     */
    public void setAdStatus(Integer adStatus) {
        this.adStatus = adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.platform_type
     *
     * @return the value of b_adverisement.platform_type
     *
     * @mbg.generated
     */
    public Integer getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.platform_type
     *
     * @param platformType the value for b_adverisement.platform_type
     *
     * @mbg.generated
     */
    public void setPlatformType(Integer platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.create_time
     *
     * @return the value of b_adverisement.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.create_time
     *
     * @param createTime the value for b_adverisement.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_adverisement.update_time
     *
     * @return the value of b_adverisement.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_adverisement.update_time
     *
     * @param updateTime the value for b_adverisement.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}