package com.jk51.model.treat;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class WxAutoReply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.site_id
     *
     * @mbg.generated
     */
    @JsonProperty("siteId")
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.reply_type
     *
     * @mbg.generated
     */
    @JsonProperty("replyType")
    private Integer replyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.rule_name
     *
     * @mbg.generated
     */
    @JsonProperty("ruleName")
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.keywords
     *
     * @mbg.generated
     */
    @JsonProperty("keywords")
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.del_tag
     *
     * @mbg.generated
     */
    @JsonProperty("delTag")
    private Integer delTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.create_time
     *
     * @mbg.generated
     */
    @JsonProperty("createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.update_time
     *
     * @mbg.generated
     */
    @JsonProperty("updateTime")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_autoreply.reply_content
     *
     * @mbg.generated
     */
    @JsonProperty("replyContent")
    private String replyContent;

    @JsonProperty("replyContentType")
    private Integer replyContentType;

    @JsonProperty("onOff")
    private Integer onOff;

    public Integer getOnOff() {
        return onOff;
    }

    public void setOnOff(Integer onOff) {
        this.onOff = onOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.id
     *
     * @return the value of b_wx_autoreply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.id
     *
     * @param id the value for b_wx_autoreply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.site_id
     *
     * @return the value of b_wx_autoreply.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.site_id
     *
     * @param siteId the value for b_wx_autoreply.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.reply_type
     *
     * @return the value of b_wx_autoreply.reply_type
     *
     * @mbg.generated
     */
    public Integer getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.reply_type
     *
     * @param replyType the value for b_wx_autoreply.reply_type
     *
     * @mbg.generated
     */
    public void setReplyType(Integer replyType) {
        this.replyType = replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.rule_name
     *
     * @return the value of b_wx_autoreply.rule_name
     *
     * @mbg.generated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.rule_name
     *
     * @param ruleName the value for b_wx_autoreply.rule_name
     *
     * @mbg.generated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.keywords
     *
     * @return the value of b_wx_autoreply.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.keywords
     *
     * @param keywords the value for b_wx_autoreply.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.del_tag
     *
     * @return the value of b_wx_autoreply.del_tag
     *
     * @mbg.generated
     */
    public Integer getDelTag() {
        return delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.del_tag
     *
     * @param delTag the value for b_wx_autoreply.del_tag
     *
     * @mbg.generated
     */
    public void setDelTag(Integer delTag) {
        this.delTag = delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.create_time
     *
     * @return the value of b_wx_autoreply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.create_time
     *
     * @param createTime the value for b_wx_autoreply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.update_time
     *
     * @return the value of b_wx_autoreply.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.update_time
     *
     * @param updateTime the value for b_wx_autoreply.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_autoreply.reply_content
     *
     * @return the value of b_wx_autoreply.reply_content
     *
     * @mbg.generated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_autoreply.reply_content
     *
     * @param replyContent the value for b_wx_autoreply.reply_content
     *
     * @mbg.generated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    public Integer getReplyContentType() {
        return replyContentType;
    }

    public void setReplyContentType(Integer replyContentType) {
        this.replyContentType = replyContentType;
    }
}
