package com.jk51.model.treat;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class WXPicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.pic_id
     *
     * @mbg.generated
     */
    @JsonProperty("picId")
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.site_id
     *
     * @mbg.generated
     */
    @JsonProperty("siteId")
    private Integer siteId;

    @JsonProperty("mediaId")
    private String mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.pic_url
     *
     * @mbg.generated
     */
    @JsonProperty("picUrl")
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.tencent_pic_url
     *
     * @mbg.generated
     */
    @JsonProperty("tencentPicUrl")
    private String tencentPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.status
     *
     * @mbg.generated
     */
    @JsonProperty("status")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.create_time
     *
     * @mbg.generated
     */
    @JsonProperty("createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.update_time
     *
     * @mbg.generated
     */
    @JsonProperty("updateTime")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic.md5key
     *
     * @mbg.generated
     */
    @JsonProperty("md5key")
    private String md5key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.pic_id
     *
     * @return the value of b_wx_pic.pic_id
     *
     * @mbg.generated
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.pic_id
     *
     * @param picId the value for b_wx_pic.pic_id
     *
     * @mbg.generated
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.site_id
     *
     * @return the value of b_wx_pic.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.site_id
     *
     * @param siteId the value for b_wx_pic.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.pic_url
     *
     * @return the value of b_wx_pic.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.pic_url
     *
     * @param picUrl the value for b_wx_pic.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.tencent_pic_url
     *
     * @return the value of b_wx_pic.tencent_pic_url
     *
     * @mbg.generated
     */
    public String getTencentPicUrl() {
        return tencentPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.tencent_pic_url
     *
     * @param tencentPicUrl the value for b_wx_pic.tencent_pic_url
     *
     * @mbg.generated
     */
    public void setTencentPicUrl(String tencentPicUrl) {
        this.tencentPicUrl = tencentPicUrl == null ? null : tencentPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.status
     *
     * @return the value of b_wx_pic.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.status
     *
     * @param status the value for b_wx_pic.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.create_time
     *
     * @return the value of b_wx_pic.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.create_time
     *
     * @param createTime the value for b_wx_pic.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.update_time
     *
     * @return the value of b_wx_pic.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.update_time
     *
     * @param updateTime the value for b_wx_pic.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic.md5key
     *
     * @return the value of b_wx_pic.md5key
     *
     * @mbg.generated
     */
    public String getMd5key() {
        return md5key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic.md5key
     *
     * @param md5key the value for b_wx_pic.md5key
     *
     * @mbg.generated
     */
    public void setMd5key(String md5key) {
        this.md5key = md5key == null ? null : md5key.trim();
    }


    public String getMediaId() {
        return mediaId;
    }

    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }
}
