package com.jk51.model.treat;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class WXPictureContext {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.pic_context_id
     *
     * @mbg.generated
     */
    private Integer picContextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.site_id
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.title
     *
     * @mbg.generated
     */
    @JsonProperty("title")
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.author
     *
     * @mbg.generated
     */
    @JsonProperty("author")
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.pic_url
     *
     * @mbg.generated
     */
    @JsonProperty("img_src")
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.show_in_context
     *
     * @mbg.generated
     */
    @JsonProperty("show_cover_pic")
    private Integer showInContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.context_source_url
     *
     * @mbg.generated
     */
    private String contextSourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.digest
     *
     * @mbg.generated
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.wx_media_id
     *
     * @mbg.generated
     */
    @JsonProperty("thumb_media_id")
    private String wxMediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_wx_pic_context.context
     *
     * @mbg.generated
     */
    @JsonProperty("content")
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.pic_context_id
     *
     * @return the value of b_wx_pic_context.pic_context_id
     *
     * @mbg.generated
     */
    public Integer getPicContextId() {
        return picContextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.pic_context_id
     *
     * @param picContextId the value for b_wx_pic_context.pic_context_id
     *
     * @mbg.generated
     */
    public void setPicContextId(Integer picContextId) {
        this.picContextId = picContextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.site_id
     *
     * @return the value of b_wx_pic_context.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.site_id
     *
     * @param siteId the value for b_wx_pic_context.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.title
     *
     * @return the value of b_wx_pic_context.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.title
     *
     * @param title the value for b_wx_pic_context.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.author
     *
     * @return the value of b_wx_pic_context.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.author
     *
     * @param author the value for b_wx_pic_context.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.pic_url
     *
     * @return the value of b_wx_pic_context.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.pic_url
     *
     * @param picUrl the value for b_wx_pic_context.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.show_in_context
     *
     * @return the value of b_wx_pic_context.show_in_context
     *
     * @mbg.generated
     */
    public Integer getShowInContext() {
        return showInContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.show_in_context
     *
     * @param showInContext the value for b_wx_pic_context.show_in_context
     *
     * @mbg.generated
     */
    public void setShowInContext(Integer showInContext) {
        this.showInContext = showInContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.context_source_url
     *
     * @return the value of b_wx_pic_context.context_source_url
     *
     * @mbg.generated
     */
    public String getContextSourceUrl() {
        return contextSourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.context_source_url
     *
     * @param contextSourceUrl the value for b_wx_pic_context.context_source_url
     *
     * @mbg.generated
     */
    public void setContextSourceUrl(String contextSourceUrl) {
        this.contextSourceUrl = contextSourceUrl == null ? null : contextSourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.digest
     *
     * @return the value of b_wx_pic_context.digest
     *
     * @mbg.generated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.digest
     *
     * @param digest the value for b_wx_pic_context.digest
     *
     * @mbg.generated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.create_time
     *
     * @return the value of b_wx_pic_context.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.create_time
     *
     * @param createTime the value for b_wx_pic_context.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.update_time
     *
     * @return the value of b_wx_pic_context.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.update_time
     *
     * @param updateTime the value for b_wx_pic_context.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.status
     *
     * @return the value of b_wx_pic_context.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.status
     *
     * @param status the value for b_wx_pic_context.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.wx_media_id
     *
     * @return the value of b_wx_pic_context.wx_media_id
     *
     * @mbg.generated
     */
    public String getWxMediaId() {
        return wxMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.wx_media_id
     *
     * @param wxMediaId the value for b_wx_pic_context.wx_media_id
     *
     * @mbg.generated
     */
    public void setWxMediaId(String wxMediaId) {
        this.wxMediaId = wxMediaId == null ? null : wxMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_wx_pic_context.context
     *
     * @return the value of b_wx_pic_context.context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_wx_pic_context.context
     *
     * @param context the value for b_wx_pic_context.context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}