package com.jk51.model.registration.models;

public class ServceDoctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.id
     *
     * @mbg.generated
     */
    private Integer id;

    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.site_id
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.doctor_img
     *
     * @mbg.generated
     */
    private String doctorImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.doctor_phone
     *
     * @mbg.generated
     */
    private String doctorPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.doctor_position
     *
     * @mbg.generated
     */
    private String doctorPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.honour
     *
     * @mbg.generated
     */
    private String honour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.stores
     *
     * @mbg.generated
     */
    private String stores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_doctor.remark
     *
     * @mbg.generated
     */
    private String remark;


    private String commentFen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.id
     *
     * @return the value of b_servce_doctor.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.id
     *
     * @param id the value for b_servce_doctor.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.site_id
     *
     * @return the value of b_servce_doctor.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.site_id
     *
     * @param siteId the value for b_servce_doctor.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.goods_id
     *
     * @return the value of b_servce_doctor.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.goods_id
     *
     * @param goodsId the value for b_servce_doctor.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.doctor_img
     *
     * @return the value of b_servce_doctor.doctor_img
     *
     * @mbg.generated
     */
    public String getDoctorImg() {
        return doctorImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.doctor_img
     *
     * @param doctorImg the value for b_servce_doctor.doctor_img
     *
     * @mbg.generated
     */
    public void setDoctorImg(String doctorImg) {
        this.doctorImg = doctorImg == null ? null : doctorImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.doctor_name
     *
     * @return the value of b_servce_doctor.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.doctor_name
     *
     * @param doctorName the value for b_servce_doctor.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.doctor_phone
     *
     * @return the value of b_servce_doctor.doctor_phone
     *
     * @mbg.generated
     */
    public String getDoctorPhone() {
        return doctorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.doctor_phone
     *
     * @param doctorPhone the value for b_servce_doctor.doctor_phone
     *
     * @mbg.generated
     */
    public void setDoctorPhone(String doctorPhone) {
        this.doctorPhone = doctorPhone == null ? null : doctorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.sex
     *
     * @return the value of b_servce_doctor.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.sex
     *
     * @param sex the value for b_servce_doctor.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.doctor_position
     *
     * @return the value of b_servce_doctor.doctor_position
     *
     * @mbg.generated
     */
    public String getDoctorPosition() {
        return doctorPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.doctor_position
     *
     * @param doctorPosition the value for b_servce_doctor.doctor_position
     *
     * @mbg.generated
     */
    public void setDoctorPosition(String doctorPosition) {
        this.doctorPosition = doctorPosition == null ? null : doctorPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.status
     *
     * @return the value of b_servce_doctor.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.status
     *
     * @param status the value for b_servce_doctor.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.describe
     *
     * @return the value of b_servce_doctor.describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.describe
     *
     * @param describe the value for b_servce_doctor.describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.honour
     *
     * @return the value of b_servce_doctor.honour
     *
     * @mbg.generated
     */
    public String getHonour() {
        return honour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.honour
     *
     * @param honour the value for b_servce_doctor.honour
     *
     * @mbg.generated
     */
    public void setHonour(String honour) {
        this.honour = honour == null ? null : honour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.introduce
     *
     * @return the value of b_servce_doctor.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.introduce
     *
     * @param introduce the value for b_servce_doctor.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.stores
     *
     * @return the value of b_servce_doctor.stores
     *
     * @mbg.generated
     */
    public String getStores() {
        return stores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.stores
     *
     * @param stores the value for b_servce_doctor.stores
     *
     * @mbg.generated
     */
    public void setStores(String stores) {
        this.stores = stores == null ? null : stores.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_doctor.remark
     *
     * @return the value of b_servce_doctor.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_doctor.remark
     *
     * @param remark the value for b_servce_doctor.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getCommentFen() {
        return commentFen;
    }

    public void setCommentFen(String commentFen) {
        this.commentFen = commentFen;
    }

    public Integer getDoctorId() {
        return id;
    }

    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
}