package com.jk51.model.registration.models;

import java.util.Date;

public class ServceUseDetail {

    private String servUserIds;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.site_id
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.site_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.templateNo
     *
     * @mbg.generated
     */
    private String templateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.mine_classes_id
     *
     * @mbg.generated
     */
    private Integer mineClassesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.use_count
     *
     * @mbg.generated
     */
    private Integer useCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.account_source
     *
     * @mbg.generated
     */
    private Integer accountSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.use_time
     *
     * @mbg.generated
     */
    private Date useTime;
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_use_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.id
     *
     * @return the value of b_servce_use_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.id
     *
     * @param id the value for b_servce_use_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.site_id
     *
     * @return the value of b_servce_use_detail.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.site_id
     *
     * @param siteId the value for b_servce_use_detail.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.template_id
     *
     * @return the value of b_servce_use_detail.template_id
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.template_id
     *
     * @param templateNo the value for b_servce_use_detail.template_id
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.mine_classes_id
     *
     * @return the value of b_servce_use_detail.mine_classes_id
     *
     * @mbg.generated
     */
    public Integer getMineClassesId() {
        return mineClassesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.mine_classes_id
     *
     * @param mineClassesId the value for b_servce_use_detail.mine_classes_id
     *
     * @mbg.generated
     */
    public void setMineClassesId(Integer mineClassesId) {
        this.mineClassesId = mineClassesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.use_count
     *
     * @return the value of b_servce_use_detail.use_count
     *
     * @mbg.generated
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.use_count
     *
     * @param useCount the value for b_servce_use_detail.use_count
     *
     * @mbg.generated
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.account_source
     *
     * @return the value of b_servce_use_detail.account_source
     *
     * @mbg.generated
     */
    public Integer getAccountSource() {
        return accountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.account_source
     *
     * @param accountSource the value for b_servce_use_detail.account_source
     *
     * @mbg.generated
     */
    public void setAccountSource(Integer accountSource) {
        this.accountSource = accountSource;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.goods_id
     *
     * @return the value of b_servce_use_detail.goods_id
     *
     * @mbg.generated
     */

    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.goods_id
     *
     * @param goodsId the value for b_servce_use_detail.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.use_time
     *
     * @return the value of b_servce_use_detail.use_time
     *
     * @mbg.generated
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.use_time
     *
     * @param useTime the value for b_servce_use_detail.use_time
     *
     * @mbg.generated
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.create_time
     *
     * @return the value of b_servce_use_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.create_time
     *
     * @param createTime the value for b_servce_use_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_use_detail.update_time
     *
     * @return the value of b_servce_use_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_use_detail.update_time
     *
     * @param updateTime the value for b_servce_use_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public String getServUserIds() {
        return servUserIds;
    }

    public void setServUserIds(String servUserIds) {
        this.servUserIds = servUserIds;
    }
}