package com.jk51.model.registration.models;

import java.util.Date;

public class ServceOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.site_id
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.trades_id
     *
     * @mbg.generated
     */
    private String tradesId;
    private String bookingNo;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.use_detail_id
     *
     * @mbg.generated
     */
    private Integer useDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.use_count
     *
     * @mbg.generated
     */
    private Integer useCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.serve_status
     *
     * @mbg.generated
     */
    private Integer serveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.schedule_person_id
     *
     * @mbg.generated
     */
    private Integer schedulePersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.diagnose_status
     *
     * @mbg.generated
     */
    private Integer diagnoseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_order.disease_info
     *
     * @mbg.generated
     */
    private String diseaseInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.id
     *
     * @return the value of b_servce_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.id
     *
     * @param id the value for b_servce_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.site_id
     *
     * @return the value of b_servce_order.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.site_id
     *
     * @param siteId the value for b_servce_order.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public String getBookingNo() {
        return bookingNo;
    }

    public void setBookingNo(String bookingNo) {
        this.bookingNo = bookingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.store_id
     *
     * @return the value of b_servce_order.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.store_id
     *
     * @param storeId the value for b_servce_order.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.trades_id
     *
     * @return the value of b_servce_order.trades_id
     *
     * @mbg.generated
     */
    public String getTradesId() {
        return tradesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.trades_id
     *
     * @param tradesId the value for b_servce_order.trades_id
     *
     * @mbg.generated
     */
    public void setTradesId(String tradesId) {
        this.tradesId = tradesId == null ? null : tradesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.use_detail_id
     *
     * @return the value of b_servce_order.use_detail_id
     *
     * @mbg.generated
     */
    public Integer getUseDetailId() {
        return useDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.use_detail_id
     *
     * @param useDetailId the value for b_servce_order.use_detail_id
     *
     * @mbg.generated
     */
    public void setUseDetailId(Integer useDetailId) {
        this.useDetailId = useDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.use_count
     *
     * @return the value of b_servce_order.use_count
     *
     * @mbg.generated
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.use_count
     *
     * @param useCount the value for b_servce_order.use_count
     *
     * @mbg.generated
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.amount
     *
     * @return the value of b_servce_order.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.amount
     *
     * @param amount the value for b_servce_order.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.serve_status
     *
     * @return the value of b_servce_order.serve_status
     *
     * @mbg.generated
     */
    public Integer getServeStatus() {
        return serveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.serve_status
     *
     * @param serveStatus the value for b_servce_order.serve_status
     *
     * @mbg.generated
     */
    public void setServeStatus(Integer serveStatus) {
        this.serveStatus = serveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.schedule_person_id
     *
     * @return the value of b_servce_order.schedule_person_id
     *
     * @mbg.generated
     */
    public Integer getSchedulePersonId() {
        return schedulePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.schedule_person_id
     *
     * @param schedulePersonId the value for b_servce_order.schedule_person_id
     *
     * @mbg.generated
     */
    public void setSchedulePersonId(Integer schedulePersonId) {
        this.schedulePersonId = schedulePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.goods_id
     *
     * @return the value of b_servce_order.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.goods_id
     *
     * @param goodsId the value for b_servce_order.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.diagnose_status
     *
     * @return the value of b_servce_order.diagnose_status
     *
     * @mbg.generated
     */
    public Integer getDiagnoseStatus() {
        return diagnoseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.diagnose_status
     *
     * @param diagnoseStatus the value for b_servce_order.diagnose_status
     *
     * @mbg.generated
     */
    public void setDiagnoseStatus(Integer diagnoseStatus) {
        this.diagnoseStatus = diagnoseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.create_time
     *
     * @return the value of b_servce_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.create_time
     *
     * @param createTime the value for b_servce_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.update_time
     *
     * @return the value of b_servce_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.update_time
     *
     * @param updateTime the value for b_servce_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_order.disease_info
     *
     * @return the value of b_servce_order.disease_info
     *
     * @mbg.generated
     */
    public String getDiseaseInfo() {
        return diseaseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_order.disease_info
     *
     * @param diseaseInfo the value for b_servce_order.disease_info
     *
     * @mbg.generated
     */
    public void setDiseaseInfo(String diseaseInfo) {
        this.diseaseInfo = diseaseInfo == null ? null : diseaseInfo.trim();
    }
}