package com.jk51.model.registration.models;

import java.util.Date;
import java.util.List;

public class ServceTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.site_id
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.template_id
     *
     * @mbg.generated
     */
    private String templateNo;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.account_source
     *
     * @mbg.generated
     */
    private Integer accountSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_servce_template.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;


    private List<ServceTemplate> temPlateList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.id
     *
     * @return the value of b_servce_template.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.id
     *
     * @param id the value for b_servce_template.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.site_id
     *
     * @return the value of b_servce_template.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.site_id
     *
     * @param siteId the value for b_servce_template.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.store_id
     *
     * @return the value of b_servce_template.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.store_id
     *
     * @param storeId the value for b_servce_template.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.template_id
     *
     * @return the value of b_servce_template.template_id
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.template_id
     *
     * @param templateNo the value for b_servce_template.template_id
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.start_time
     *
     * @return the value of b_servce_template.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.start_time
     *
     * @param startTime the value for b_servce_template.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.end_time
     *
     * @return the value of b_servce_template.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.end_time
     *
     * @param endTime the value for b_servce_template.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.account_source
     *
     * @return the value of b_servce_template.account_source
     *
     * @mbg.generated
     */
    public Integer getAccountSource() {
        return accountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.account_source
     *
     * @param accountSource the value for b_servce_template.account_source
     *
     * @mbg.generated
     */
    public void setAccountSource(Integer accountSource) {
        this.accountSource = accountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.is_del
     *
     * @return the value of b_servce_template.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.is_del
     *
     * @param isDel the value for b_servce_template.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.create_time
     *
     * @return the value of b_servce_template.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.create_time
     *
     * @param createTime the value for b_servce_template.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_servce_template.update_time
     *
     * @return the value of b_servce_template.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_servce_template.update_time
     *
     * @param updateTime the value for b_servce_template.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<ServceTemplate> getTemPlateList() {
        return temPlateList;
    }

    public void setTemPlateList(List<ServceTemplate> temPlateList) {
        this.temPlateList = temPlateList;
    }
}